# --------------
# -- Settings --
# --------------

# If you are hosting in a sub-folder, for example: https://mlh.github.io/mlh-hackathon-boilerplate/,
# you must specify it as the baseurl
# If you hosting as a root, for example: htttps://[github username].github.io, then leave it blank
baseurl: "/mlh-hackathon-boilerplate"

# uncomment the next line if you are hosting as a root and not sub-folder
# for example, when runnig locally at http://127.0.0.1:4000/
# baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://mlh.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "TuringHacX | October 2023"
  description: "This is a placeholder website for upcoming hackathon at Pandit Deendayal Energy University."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "TuringHacX"
  description: "This is a placeholder website for upcoming hackathon at Pandit Deendayal Energy University."
  date:        "2nd October 2023"
  location:    "Pandit Deendayal Energy University, Gandhinagar, India"

  trust_badge:
    year:   "2023"  # season year
    region: "apac"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        my_mlh:
          client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Sponsor"
        href: "mailto:navdharesaurav2003@gmail.com"

  about:
    description: >
      TuringHacX is a hackathon hosted at Pandit Deendayal Energy University.
      Hackathon is in initial stages of ideation, You can check back on 2nd October 2023 for Major updates of the hackathon.
      TuringHacX will be an innovative hackathon where you will be given real life problem statements at the venue of hackathon, you need to ideate and develop a good solution during the hacking hours


  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "LEARN."
        description: >
          Ideate and Learn about real life problems
      - image: "images/image2.png"
        title: "BUILD."
        description: >
          Build your solution making yourself as the solution provider
      - image: "images/image3.png"
        title: "SHARE."
        description: >
          Share your application world wide by contributing it to the community

  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        It will only cost a few kbs of data (only to apply)
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university.
    - question: "Where is the event?"
      answer: >
        The event is being hosted at Pandit Deendayal Energy University, Gandhinagar, Gujarat, India.
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
